bricc:
    config:
        startTime:
            hours: 7
            minutes: 30
        numHours: 16
        minStartTimeInterval: 30

        specialTimings:
            - date:
                  year: 2022
                  month: 7
                  date: 26
              startTime:
                  hours: 9
                  minutes: 0
              numHours: 5

            - date:
                  year: 2022
                  month: 7
                  date: 29
              startTime:
                  hours: 10
                  minutes: 0
              numHours: 7

        numLanes: 5

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/bricc_schema"
        username: root
        password: wyandotte
server:
    port: 9090