bricc:
    config:
        startTime:
            hour: 7
            minutes: 30
        numHours: 16

        specialTimings:
            - date: 10-20-2022
              startTime:
                  hour: 9
                  minutes: 0
              numHours: 5

            - date: 10-21-2022
              startTime:
                  hour: 10
                  minutes: 0
              numHours: 7

        numLanes: 5

        announcements:
            - subject: Test Announcement
              text: This announcement is a test announcement. The purpose of it is to test the announcement functionality
spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/bricc_schema"
        username: root
        password: wyandotte
server:
    port: 9090