bricc:
    config:
        maxNumHours: 6
        defaultNumHours: 1

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/bricc_schema"
        username: root
        password: wyandotte
server:
    port: 9090